import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { WalletBalance } from '../services/wallet';
import type { TaxSummary, CostBasisMethod } from './taxCalculator';

// Brand colors
const PURPLE = [132, 95, 188] as const; // #845fbc
const DARK = [30, 30, 30] as const;
const GRAY = [120, 120, 120] as const;
const LIGHT_BG = [248, 248, 250] as const;

interface StatementData {
  address: string;
  network: string;
  period: string; // e.g. "June 2026" or "2025"
  periodType: 'monthly' | 'annual';
  balances: WalletBalance[];
  balanceValues: Record<string, number>; // address -> USD value
  totalValueUsd: number;
  homeCurrency: string;
  homeTotal: number;
  transactions: {
    date: string;
    type: string;
    tokenIn: string;
    amountIn: string;
    tokenOut: string;
    amountOut: string;
    pool?: string;
  }[];
}

interface ProofOfFundsData {
  address: string;
  network: string;
  balances: { symbol: string; amount: string; valueUsd: number }[];
  totalValueUsd: number;
  homeCurrency: string;
  homeTotal: number;
  generatedAt: string;
}

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  // Purple bar
  doc.setFillColor(...PURPLE);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 38, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Alpaca DEX', 20, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 20, 30);

  if (subtitle) {
    doc.setFontSize(9);
    doc.text(subtitle, doc.internal.pageSize.getWidth() - 20, 30, { align: 'right' });
  }

  // Reset text color
  doc.setTextColor(...DARK);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setDrawColor(220, 220, 220);
    doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);

    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(
      'Generated by Alpaca DEX — this is not a regulated financial statement.',
      20, pageHeight - 13
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 20, pageHeight - 13,
      { align: 'right' }
    );
  }
}

function shortenAddress(addr: string): string {
  if (!addr || addr.length < 16) return addr;
  return addr.slice(0, 12) + '...' + addr.slice(-8);
}

function formatCurrency(value: number, currency: string): string {
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(value);
  } catch {
    return `${currency} ${value.toFixed(2)}`;
  }
}

export function generateStatement(data: StatementData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  addHeader(doc, `${data.periodType === 'annual' ? 'Annual' : 'Monthly'} Statement`, data.period);

  let y = 50;

  // Account info box
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(20, y, pageWidth - 40, 28, 3, 3, 'F');

  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text('WALLET ADDRESS', 28, y + 8);
  doc.text('NETWORK', pageWidth / 2, y + 8);
  doc.text('PERIOD', pageWidth - 60, y + 8);

  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(shortenAddress(data.address), 28, y + 18);
  doc.text(data.network === 'main' ? 'Mainnet' : 'Testnet', pageWidth / 2, y + 18);
  doc.text(data.period, pageWidth - 60, y + 18);
  doc.setFont('helvetica', 'normal');

  y += 38;

  // Portfolio value
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text('PORTFOLIO VALUE', 20, y);
  y += 8;
  doc.setFontSize(16);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(data.homeTotal, data.homeCurrency), 20, y);
  if (data.homeCurrency !== 'USD') {
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    doc.setFont('helvetica', 'normal');
    doc.text(`(${formatCurrency(data.totalValueUsd, 'USD')})`, 20 + doc.getTextWidth(formatCurrency(data.homeTotal, data.homeCurrency)) + 5, y);
  }
  doc.setFont('helvetica', 'normal');

  y += 14;

  // Balances table
  doc.setFontSize(10);
  doc.setTextColor(...PURPLE);
  doc.setFont('helvetica', 'bold');
  doc.text('Holdings', 20, y);
  doc.setFont('helvetica', 'normal');
  y += 4;

  const balanceRows = data.balances.map(b => [
    b.symbol,
    b.amount,
    data.balanceValues[b.address] > 0
      ? formatCurrency(data.balanceValues[b.address], 'USD')
      : '—'
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Asset', 'Balance', 'USD Value']],
    body: balanceRows,
    margin: { left: 20, right: 20 },
    headStyles: {
      fillColor: [...PURPLE],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [...DARK],
    },
    alternateRowStyles: {
      fillColor: [...LIGHT_BG],
    },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { halign: 'right' },
      2: { halign: 'right', cellWidth: 40 },
    },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Transaction history
  if (data.transactions.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(10);
    doc.setTextColor(...PURPLE);
    doc.setFont('helvetica', 'bold');
    doc.text(`Transaction History (${data.transactions.length})`, 20, y);
    doc.setFont('helvetica', 'normal');
    y += 4;

    const txRows = data.transactions.map(tx => [
      tx.date,
      tx.type,
      `${tx.amountIn} ${tx.tokenIn}`,
      `${tx.amountOut} ${tx.tokenOut}`,
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Type', 'In', 'Out']],
      body: txRows,
      margin: { left: 20, right: 20 },
      headStyles: {
        fillColor: [...PURPLE],
        textColor: [255, 255, 255],
        fontSize: 8,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 7,
        textColor: [...DARK],
      },
      alternateRowStyles: {
        fillColor: [...LIGHT_BG],
      },
      columnStyles: {
        0: { cellWidth: 36 },
        1: { cellWidth: 20 },
      },
    });
  }

  // Generated timestamp
  y = (doc as any).lastAutoTable?.finalY + 10 || y + 10;
  if (y > 270) { doc.addPage(); y = 20; }
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text(`Generated: ${new Date().toISOString()}`, 20, y);

  addFooter(doc);
  return doc;
}

export function generateProofOfFunds(data: ProofOfFundsData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  addHeader(doc, 'Proof of Funds Letter', data.generatedAt);

  let y = 55;

  // Letter body
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text('Certificate of Balance', 20, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DARK);

  const lines = doc.splitTextToSize(
    `This document certifies that the digital wallet identified below held the following asset balances as of ${data.generatedAt}. ` +
    `All balances were verified on the KeetaNet blockchain (${data.network === 'main' ? 'Mainnet' : 'Testnet'}).`,
    pageWidth - 40
  );
  doc.text(lines, 20, y);
  y += lines.length * 5 + 10;

  // Wallet info
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(20, y, pageWidth - 40, 18, 3, 3, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text('WALLET ADDRESS', 28, y + 7);
  doc.setFontSize(8);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(data.address, 28, y + 14);
  doc.setFont('helvetica', 'normal');
  y += 28;

  // Balance table
  const rows = data.balances.map(b => [
    b.symbol,
    b.amount,
    b.valueUsd > 0 ? formatCurrency(b.valueUsd, 'USD') : '—',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Asset', 'Balance', 'Estimated USD Value']],
    body: rows,
    margin: { left: 20, right: 20 },
    headStyles: {
      fillColor: [...PURPLE],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [...DARK],
    },
    alternateRowStyles: {
      fillColor: [...LIGHT_BG],
    },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right', cellWidth: 50 },
    },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Total
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(20, y, pageWidth - 40, 20, 3, 3, 'F');

  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text('TOTAL ESTIMATED VALUE', 28, y + 8);

  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(data.homeTotal, data.homeCurrency), 28, y + 16);
  doc.setFont('helvetica', 'normal');

  if (data.homeCurrency !== 'USD') {
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    const mainText = formatCurrency(data.homeTotal, data.homeCurrency);
    doc.text(`(${formatCurrency(data.totalValueUsd, 'USD')})`, 28 + doc.getTextWidth(mainText) + 8, y + 16);
  }

  y += 30;

  // Verification hash
  const contentHash = btoa(JSON.stringify({
    address: data.address,
    network: data.network,
    balances: data.balances,
    totalValueUsd: data.totalValueUsd,
    generatedAt: data.generatedAt,
  })).slice(0, 32);

  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(`Verification Reference: ${contentHash}`, 20, y);
  y += 6;
  doc.text(`Timestamp: ${new Date().toISOString()}`, 20, y);
  y += 12;

  // Disclaimer
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  const disclaimer = doc.splitTextToSize(
    'DISCLAIMER: This proof of funds letter is generated based on on-chain data at the time of generation. ' +
    'Balances may change after this document was created. USD valuations are estimates based on available market data. ' +
    'This document is provided for informational purposes only and does not constitute a financial audit or guarantee.',
    pageWidth - 40
  );
  doc.text(disclaimer, 20, y);

  addFooter(doc);
  return doc;
}

// ─── Tax Report PDF ─────────────────────────────────────────────────────────

interface TaxReportPdfData {
  address: string;
  network: string;
  year: number;
  method: CostBasisMethod;
  summary: TaxSummary;
}

function formatKta(value: number): string {
  if (Math.abs(value) < 0.000001) return '0';
  return value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 });
}

function methodLabel(m: CostBasisMethod): string {
  switch (m) {
    case 'fifo': return 'FIFO (First In, First Out)';
    case 'lifo': return 'LIFO (Last In, First Out)';
    case 'hifo': return 'HIFO (Highest In, First Out)';
  }
}

export function generateTaxReport(data: TaxReportPdfData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const { summary } = data;

  addHeader(doc, `Tax Report — ${data.year}`, methodLabel(data.method));

  let y = 50;

  // Account info
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(20, y, pageWidth - 40, 28, 3, 3, 'F');

  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text('WALLET ADDRESS', 28, y + 8);
  doc.text('TAX YEAR', pageWidth / 2, y + 8);
  doc.text('COST BASIS METHOD', pageWidth - 70, y + 8);

  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(shortenAddress(data.address), 28, y + 18);
  doc.text(String(data.year), pageWidth / 2, y + 18);
  doc.text(data.method.toUpperCase(), pageWidth - 70, y + 18);
  doc.setFont('helvetica', 'normal');

  y += 38;

  // Summary section
  doc.setFontSize(10);
  doc.setTextColor(...PURPLE);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, y);
  doc.setFont('helvetica', 'normal');
  y += 8;

  // Summary cards in a 2-col layout
  const cardW = (pageWidth - 50) / 2;
  const cards = [
    { label: 'Net Gain / Loss', value: formatKta(summary.netGainLoss) + ' KTA', color: summary.netGainLoss >= 0 ? [22, 163, 74] : [220, 38, 38] },
    { label: 'Total Trades', value: String(summary.totalTrades), color: [...DARK] },
    { label: 'Realized Gains', value: formatKta(summary.totalRealizedGains) + ' KTA', color: [22, 163, 74] },
    { label: 'Realized Losses', value: formatKta(summary.totalRealizedLosses) + ' KTA', color: [220, 38, 38] },
    { label: 'Short-Term Gains', value: formatKta(summary.shortTermGains) + ' KTA', color: [...DARK] },
    { label: 'Long-Term Gains', value: formatKta(summary.longTermGains) + ' KTA', color: [...DARK] },
    { label: 'Short-Term Losses', value: formatKta(summary.shortTermLosses) + ' KTA', color: [...DARK] },
    { label: 'Long-Term Losses', value: formatKta(summary.longTermLosses) + ' KTA', color: [...DARK] },
  ];

  for (let i = 0; i < cards.length; i += 2) {
    for (let j = 0; j < 2 && i + j < cards.length; j++) {
      const card = cards[i + j];
      const x = 20 + j * (cardW + 10);

      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(x, y, cardW, 18, 2, 2, 'F');

      doc.setFontSize(7);
      doc.setTextColor(...GRAY);
      doc.text(card.label.toUpperCase(), x + 6, y + 6);

      doc.setFontSize(10);
      doc.setTextColor(card.color[0], card.color[1], card.color[2]);
      doc.setFont('helvetica', 'bold');
      doc.text(card.value, x + 6, y + 14);
      doc.setFont('helvetica', 'normal');
    }
    y += 22;
  }

  y += 6;

  // Taxable events table
  if (summary.events.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }

    doc.setFontSize(10);
    doc.setTextColor(...PURPLE);
    doc.setFont('helvetica', 'bold');
    doc.text(`Taxable Events (${summary.events.length} dispositions)`, 20, y);
    doc.setFont('helvetica', 'normal');
    y += 4;

    const rows = summary.events.map(e => [
      e.date,
      formatKta(e.amount),
      formatKta(e.costBasis),
      formatKta(e.proceeds),
      (e.gainLoss >= 0 ? '+' : '') + formatKta(e.gainLoss),
      e.holdingPeriod === 'short' ? 'Short' : 'Long',
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Amount', 'Cost Basis (KTA)', 'Proceeds (KTA)', 'Gain/Loss (KTA)', 'Term']],
      body: rows,
      margin: { left: 20, right: 20 },
      headStyles: {
        fillColor: [...PURPLE],
        textColor: [255, 255, 255],
        fontSize: 7,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 7,
        textColor: [...DARK],
      },
      alternateRowStyles: {
        fillColor: [...LIGHT_BG],
      },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'center', cellWidth: 18 },
      },
      didParseCell: (hookData: any) => {
        if (hookData.section === 'body' && hookData.column.index === 4) {
          const val = summary.events[hookData.row.index]?.gainLoss ?? 0;
          hookData.cell.styles.textColor = val >= 0 ? [22, 163, 74] : [220, 38, 38];
          hookData.cell.styles.fontStyle = 'bold';
        }
      },
    });
  }

  // Disclaimer
  y = (doc as any).lastAutoTable?.finalY + 12 || y + 12;
  if (y > 260) { doc.addPage(); y = 20; }

  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  const taxDisclaimer = doc.splitTextToSize(
    'DISCLAIMER: This tax report is generated for informational purposes only and does not constitute tax advice. ' +
    'All values are denominated in KTA (base token). Consult a qualified tax professional for your specific tax situation. ' +
    'Cost basis calculations may not reflect all transactions if trade history is incomplete.',
    pageWidth - 40
  );
  doc.text(taxDisclaimer, 20, y);

  addFooter(doc);
  return doc;
}
